### ISSUE TITLE
Kiedy project firend

### ISSUE THREAD

**Issue by Ketok4321** [mcGolab/Project-friend#1]

**Comment by mcGolab** [comment]
Gra nie ma celu więc jest bez sensu i taka gra nie będzie się fajnie sie sprzedawać (za darmo) ale udostępniłem projekt na githuba więc jak umiesz godota to projekt sobie mozesz odnowić lub zrobić swoją własną gre na podstawie tej

**Comment by teleguest** [comment]
wiesz że w języku polski można używac async i await ?

**Comment by Ketok4321** [comment]
ale nie umiem godota

**Comment by ghost** [comment]
> ale nie umiem godota

to się naucz

**Comment by Ketok4321** [comment]
telelej
